[package]
name = "tiled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.0"
serde_json = "1.0.114"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.61"
